version: '2'
services:
  elasticsearch-logs:
    container_name: elasticsearch-logs
    image: elasticsearch:5.2.0-alpine
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9201:9200"
      - "9301:9300"
  
  logstash:
    container_name: logstash
    build: /vagrant/scripts/guest/docker/logging/logstash
    volumes:
     - /vagrant/scripts/guest/docker/logging/logstash:/config-dir
     #- /vagrant/scripts/guest/docker/logging/logstash:/var/log/logstash
    depends_on:
      - elasticsearch-logs
    ports:
      - "25826:25826"
    
  kibana:
    container_name: kibana
    image: kibana:5.2.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch-logs
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-logs:9200