version: '2'
services:
  elasticsearch-logs:
    container_name: elasticsearch-logs
    build: /vagrant/scripts/guest/docker/logging/elasticsearch-logs
    ports:
      - "9201:9200"
      - "9301:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1024m
    cap_add:
      - IPC_LOCK
    restart: on-failure
  logstash:
    container_name: logstash
    build: /vagrant/scripts/guest/docker/logging/logstash
    volumes:
     - /vagrant/scripts/guest/docker/logging/logstash:/config-dir
     - /vagrant/logs:/log-dir
     #- /vagrant/scripts/guest/docker/logging/logstash:/var/log/logstash
    depends_on:
      - elasticsearch-logs
    ports:
      - "25826:25826"
    restart: on-failure
    
  kibana:
    container_name: kibana
    image: kibana:5.2.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch-logs
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-logs:9200
    restart: on-failure