version: '2'
services:
  elasticsearch-logs:
    container_name: elasticsearch-logs
    image: elasticsearch:2.3
  
  logstash:
    container_name: logstash
    image: logstash:2.3
    command: logstash -f /config-dir/logstash.conf
    volumes:
     - /vagrant/scripts/guest/docker/logging:/config-dir
    depends_on:
      - elasticsearch-logs
    ports:
      - "25826:25826"
    
  kibana:
    container_name: kibana
    image: kibana:4.5
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch-logs
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-logs:9200