FROM postgres:9.4

# This user will be created as the superuser
ENV POSTGRES_USER root
ENV POSTGRES_PASSWORD superroot

# For dev use - while in the container psql will just work (useful for the provisioning)
ENV PGUSER root
ENV PGPASSWORD superroot
